const app = document.querySelector('#app');
const homeBtn = document.querySelector('#homeBtn');
let game = null;
const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
async function api(path, options = {}) { const response = await fetch(path, { headers: { 'Content-Type': 'application/json' }, ...options }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Une erreur est survenue.'); return data; }
function renderHome() { homeBtn.hidden = true; app.innerHTML = `<section><h1>Réviser les réactions, <em>sans perdre le fil.</em></h1><p class="lede">Un labo calme pour mémoriser les noms de 73 réactions organiques. Le mode Survie est synchronisé avec un classement partagé.</p><div class="games"><button class="game" id="start"><span class="game-text"><h3>Survie</h3><p>20 associations nom ↔ réaction, corrigées côté serveur.</p></span><span class="num">01</span></button><button class="game" id="board"><span class="game-text"><h3>Classement</h3><p>Les meilleurs scores de la communauté, sous pseudonyme.</p></span><span class="num">02</span></button></div><p class="note" style="margin-top:22px">Le score n’est envoyé qu’après la partie. Aucun compte ni adresse e-mail n’est demandé.</p></section>`; document.querySelector('#start').onclick = startGame; document.querySelector('#board').onclick = showBoard; }
async function startGame() { app.innerHTML = '<p class="note">Préparation de la partie…</p>'; try { game = await api('/api/quiz/start', { method: 'POST', body: '{}' }); game.remaining = game.total; game.score = 0; homeBtn.hidden = false; homeBtn.onclick = renderHome; renderQuestion(); } catch (error) { app.innerHTML = `<p class="note">${escapeHtml(error.message)}</p>`; } }
function renderQuestion(feedback = '') { const q = game.question; app.innerHTML = `<div class="topline"><div><div class="stats"><span class="pill">Question <strong>${game.total - game.remaining + 1}/${game.total}</strong></span><span class="pill">Score <strong>${game.score || 0}</strong></span></div></div></div><div class="card"><h2>${escapeHtml(q.prompt)}</h2><p class="note">Choisissez le nom correspondant à la réaction proposée.</p><div class="select-grid">${q.options.map(option => `<button class="answer" data-id="${option.id}">${escapeHtml(option.name)}</button>`).join('')}</div><div class="feedback" aria-live="polite">${escapeHtml(feedback)}</div></div>`; document.querySelectorAll('.answer').forEach(button => { button.onclick = () => answer(Number(button.dataset.id), button); }); }
async function answer(answerId, clicked) { document.querySelectorAll('.answer').forEach(button => { button.disabled = true; }); try { const result = await api('/api/quiz/answer', { method: 'POST', body: JSON.stringify({ token: game.token, answerId }) }); clicked.classList.add(result.correct ? 'good' : 'bad'); game.score = result.score; game.remaining = game.remaining ? game.remaining - 1 : game.total - 1; if (result.done) return setTimeout(() => renderResult(result), 450); setTimeout(() => { game.question = result.question; renderQuestion(result.correct ? 'Bonne réponse.' : 'Réponse enregistrée.'); }, 450); } catch (error) { renderQuestion(error.message); } }
async function renderResult(result) { app.innerHTML = `<section class="result"><p class="note">Partie terminée</p><div class="score">${result.score}/${result.total}</div><h2>Votre score est prêt.</h2><p class="lede" style="margin-left:auto;margin-right:auto">Ajoutez un pseudonyme pour apparaître dans le classement partagé.</p><form id="scoreForm"><input id="name" maxlength="20" required placeholder="Pseudonyme" aria-label="Pseudonyme" style="padding:12px;border:1px solid var(--line);border-radius:6px;width:min(100%,280px);font:inherit"><button class="primary" type="submit" style="margin-left:6px">Publier</button></form><div class="feedback" id="resultFeedback"></div><button class="back" id="again">Rejouer</button></section>`; document.querySelector('#scoreForm').onsubmit = async event => { event.preventDefault(); const feedback = document.querySelector('#resultFeedback'); try { await api('/api/leaderboard', { method: 'POST', body: JSON.stringify({ name: document.querySelector('#name').value, score: result.score, total: result.total, completionToken: result.completionToken }) }); feedback.textContent = 'Publié dans le classement.'; document.querySelector('#scoreForm').remove(); } catch (error) { feedback.textContent = error.message; } }; document.querySelector('#again').onclick = startGame; }
async function showBoard() { homeBtn.hidden = false; homeBtn.onclick = renderHome; app.innerHTML = '<p class="note">Chargement du classement…</p>'; try { const data = await api('/api/leaderboard'); app.innerHTML = `<section><button class="back" id="boardBack">← Accueil</button><h1>Classement <em>partagé.</em></h1><p class="lede">Les scores sont vérifiés par le serveur et affichés sous pseudonyme.</p><div class="games">${data.entries.length ? data.entries.map((entry, index) => `<div class="game"><span class="game-text"><h3>${index + 1}. ${escapeHtml(entry.name)}</h3><p>${new Date(entry.createdAt).toLocaleDateString('fr-FR')}</p></span><span class="num">${entry.score}/${entry.total}</span></div>`).join('') : '<p class="note">Aucun score pour le moment.</p>'}</div></section>`; document.querySelector('#boardBack').onclick = renderHome; } catch (error) { app.innerHTML = `<p class="note">${escapeHtml(error.message)}</p>`; } }
renderHome();
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js').catch(() => {}));
