const state={data:[],route:'catalogue',query:'',family:'Toutes',quiz:null,serverQuiz:null,leaderboard:[]};
const scoreKey='reactions-labo-score-v2';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const pick=(a,n)=>shuffle(a).slice(0,n);
const loadScore=()=>JSON.parse(localStorage.getItem(scoreKey)||'{"pseudo":"","points":0,"correct":0,"played":0,"best":0,"survival":0}');
const saveScore=s=>localStorage.setItem(scoreKey,JSON.stringify(s));
const families=()=>['Toutes','Oxydations','Réductions','Réarrangements','Condensations','Couplages','Additions','Cyclisations','Substitutions','Autres'];
function family(n){let s=n.toLowerCase();if(/oxid|oxyd|swern|dess-martin|oppenauer|jones|wacker|malaprade|baeyer/.test(s))return'Oxydations';if(/reduction|réduction|luche|birch|clemmensen|wolff/.test(s))return'Réductions';if(/rearrangement|réarrangement|cope|pinacol|beckmann|curtius|hofmann/.test(s))return'Réarrangements';if(/condensation|aldol|mannich|kn[oö]evenagel|benzoin|claisen/.test(s))return'Condensations';if(/coupling|couplage|suzuki|stille|negishi|sonogashira|heck/.test(s))return'Couplages';if(/addition|grignard|michael|reformatsky|stetter/.test(s))return'Additions';if(/cyclization|cyclisation|diels|paal|prins|nazarov/.test(s))return'Cyclisations';if(/substitution|appell|finkelstein|williamson|mitsunobu|sandmeyer/.test(s))return'Substitutions';return'Autres'}
function image(x,key,label){return `<img src="${esc(x[key])}" alt="${esc(label)}" onerror="this.outerHTML='<div class=\'visual-fallback\'><span>R</span><small>schéma indisponible</small></div>'">`}
function header(title,eyebrow=''){return `<div class="back"><a href="#catalogue">← Catalogue</a><span>${eyebrow||title}</span></div>`}
function catalogue(){let visible=state.data.filter(x=>(state.family==='Toutes'||family(x.name)===state.family)&&x.name.toLowerCase().includes(state.query.toLowerCase()));return `<section class="hero"><div><p class="eyebrow">01 / bibliothèque</p><h1>Le nom est une porte<br><i>vers le mécanisme.</i></h1><p class="intro">Un atlas clair pour reconnaître, comprendre et mémoriser les grandes réactions de chimie organique.</p></div><div class="hero-note"><span class="orb">${state.data.length}</span><p>fiches<br><b>à explorer</b></p></div></section><section class="toolbar"><label class="search"><span>⌕</span><input id="search" value="${esc(state.query)}" placeholder="Rechercher une réaction…"></label><div class="filters">${families().map(f=>`<button class="filter ${state.family===f?'active':''}" data-family="${f}">${f}</button>`).join('')}</div></section><div class="catalog-meta"><span><b>${visible.length}</b> réactions</span><span>Trié par nom</span></div><div class="catalog">${visible.map(x=>`<a class="reaction-row" href="#reaction-${x.id}"><span class="index">${String(x.id).padStart(2,'0')}</span><span class="row-main"><strong>${esc(x.name)}</strong><small>${family(x.name)} · fiche de révision</small></span><span class="arrow">↗</span></a>`).join('')}</div>`}
function detail(x){return `${header('',String(x.id).padStart(2,'0')+' / 73')}<article class="detail"><div class="detail-head"><div><p class="eyebrow">fiche de révision · ${family(x.name)}</p><h1>${esc(x.name)}</h1><p class="intro">Associez le nom, le schéma et le mécanisme dans la même image mentale.</p></div><div class="detail-badge">${String(x.id).padStart(2,'0')}</div></div><div class="visual-grid"><div class="visual"><span class="visual-label">Schéma de réaction</span>${image(x,'image_schema','Schéma de '+x.name)}</div><div class="visual"><span class="visual-label">Mécanisme</span>${image(x,'image_mecanisme','Mécanisme de '+x.name)}</div></div><div class="detail-tip"><span>À retenir</span><p>Vérifiez-vous avec les quatre modes d'entraînement.</p></div><a class="button" href="#games">S'entraîner sur les réactions <span>→</span></a></article>`}
function games(){return `${header('','02 / entraînement')}<section class="hero compact"><div><p class="eyebrow">02 / entraînement</p><h1>Quatre façons de<br><i>faire le lien.</i></h1><p class="intro">Retrouvez les modes originaux : rapidité, mémoire, mécanisme et survie.</p></div></section><div class="game-grid"><a class="game-card" href="#quiz"><span class="game-index">01</span><h2>QCM chronométré</h2><p>Identifier le schéma en 15 secondes.</p><b>Jouer →</b></a><a class="game-card" href="#memory"><span class="game-index">02</span><h2>Memory</h2><p>Associer les noms à leurs schémas.</p><b>Jouer →</b></a><a class="game-card" href="#mechanism"><span class="game-index">03</span><h2>Mécanisme</h2><p>Relier une réaction à son mécanisme global.</p><b>Jouer →</b></a><a class="game-card dark" href="#survival"><span class="game-index">04</span><h2>Mode survie</h2><p>Une erreur termine la série. Battez votre record.</p><b>Jouer →</b></a></div>`}
function options(cur){return shuffle([cur,...pick(state.data.filter(x=>x.id!==cur.id),3)])}
function quiz(survive=false){
 if(!survive&&!state.serverQuiz)return `${header('','QCM chronométré')}<section class="quiz-intro"><p class="eyebrow">QCM chronométré</p><h1>Un score <i>vérifié.</i></h1><p class="intro">Répondez à une série de questions validée par le serveur, puis inscrivez votre résultat au classement partagé.</p><div class="quiz-start"><label for="server-name">Votre pseudo (optionnel)</label><input id="server-name" maxlength="20" placeholder="Curieux" autocomplete="nickname"><button class="button" id="server-start">Commencer la partie <span>→</span></button><small>20 questions · les réponses et le résultat final sont vérifiés côté serveur.</small></div></section>`;
 if(!survive)return serverQuizView();
 if(!state.quiz||state.quiz.mode!=='survival'){let cur=state.data[Math.floor(Math.random()*state.data.length)];state.quiz={mode:'survival',cur,score:0,streak:0,number:1};}
 let q=state.quiz,opts=options(q.cur);return `${header('','mode survie')}<div class="quiz-top"><span>Question ${q.number}</span><b>${q.score} points</b><span>Record local : ${loadScore().survival}</span></div><section class="question"><p class="eyebrow">Quel est le nom de cette réaction&nbsp;?</p><div class="question-visual">${image(q.cur,'image_schema','Schéma de '+q.cur.name)}</div><div class="choices">${opts.map(o=>`<button class="choice" data-answer="${o.id}">${esc(o.name)}</button>`).join('')}</div><div id="feedback" class="feedback">Une erreur termine la partie.</div></section>`;
}
function serverQuizView(){let q=state.serverQuiz,cur=state.data.find(x=>x.id===q.question.id)||q.question; if(q.done)return `${header('','QCM terminé')}<section class="quiz-intro"><p class="eyebrow">Partie terminée</p><h1>${q.score} / ${q.total}<br><i>réponses justes.</i></h1><p class="intro">${q.submitted?'Votre score est visible dans le classement partagé.':'Votre résultat est prêt à être publié dans le classement partagé.'}</p><div class="quiz-start">${q.submitted?'<a class="button" href="#score">Voir le classement <span>→</span></a>':`<label for="leader-name">Pseudo à afficher</label><input id="leader-name" maxlength="20" value="${esc(q.name||'')||'Curieux'}" placeholder="Curieux" autocomplete="nickname"><button class="button" id="server-submit">Publier mon score <span>→</span></button><div id="submit-feedback" class="feedback"></div>`}</div></section>`; return `${header('','QCM vérifié')}<div class="quiz-top"><span>Question ${q.answered+1} / ${q.total}</span><b>${q.score} point${q.score>1?'s':''}</b><span>${q.misses} erreur${q.misses>1?'s':''}</span></div><section class="question"><p class="eyebrow">Quel est le nom de cette réaction&nbsp;?</p><div class="question-visual">${image(cur,'image_schema','Schéma de '+cur.name)}</div><div class="choices">${q.question.options.map(o=>`<button class="choice" data-server-answer="${o.id}">${esc(o.name)}</button>`).join('')}</div><div id="feedback" class="feedback">Le résultat sera validé par le serveur.</div></section>`}
async function startServerQuiz(){const name=document.querySelector('#server-name')?.value.trim()||'';const r=await fetch('/api/quiz/start',{method:'POST'});if(!r.ok)throw new Error('API indisponible');const data=await r.json();state.serverQuiz={...data,answered:0,score:0,misses:0,name};location.hash='quiz';render()}
async function serverAnswer(id){document.querySelectorAll('[data-server-answer]').forEach(b=>b.disabled=true);const q=state.serverQuiz;const r=await fetch('/api/quiz/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:q.token,answerId:id})});const data=await r.json();if(!r.ok){document.querySelector('#feedback').textContent=data.error||'Réponse refusée.';return}q.answered++;q.score=data.score;q.misses=data.misses;const fb=document.querySelector('#feedback');if(fb)fb.textContent=data.correct?'Bonne réponse.':'Réponse incorrecte.';if(data.done){q.done=true;q.total=data.total;q.completionToken=data.completionToken;setTimeout(render,500)}else{q.question=data.question;setTimeout(render,500)}}
async function submitServerScore(){const q=state.serverQuiz;const name=document.querySelector('#leader-name')?.value.trim()||'Curieux';const fb=document.querySelector('#submit-feedback');const r=await fetch('/api/leaderboard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,score:q.score,total:q.total,completionToken:q.completionToken})});const data=await r.json();if(!r.ok){if(fb)fb.textContent=data.error||'Publication impossible.';return}state.leaderboard=data.entries||[];q.name=name;q.submitted=true;render()}

function memory(){let chosen=pick(state.data,6);memCards=shuffle(chosen.flatMap(x=>[{...x,type:'name'},{...x,type:'img'}]));open=[];moves=0;found=0;return `${header('','memory / paires')}<section class="question"><p class="eyebrow">Retrouvez les six paires</p><div class="memory">${memCards.map((_,i)=>`<button class="mem" data-i="${i}">✦</button>`).join('')}</div><div id="mfeedback" class="feedback">Trouvées : 0 / 6 · Coups : 0</div></section>`}
function mechanism(){let cur=state.data[Math.floor(Math.random()*state.data.length)];return `${header('','mécanisme / association')}<section class="question"><p class="eyebrow">Quel nom correspond à ce mécanisme&nbsp;?</p><div class="question-visual">${image(cur,'image_mecanisme','Mécanisme')}</div><div class="choices">${options(cur).map(o=>`<button class="choice" data-answer="${o.id}">${esc(o.name)}</button>`).join('')}</div><div id="feedback" class="feedback">Le mécanisme est fourni comme image globale.</div></section>`}
function score(){let s=loadScore();return `${header('','03 / mon score')}<section class="score-page"><p class="eyebrow">03 / mon score</p><h1>Votre carnet<br><i>de progression.</i></h1><div class="score-card"><div class="avatar">${esc((s.pseudo||'Vous').slice(0,2).toUpperCase())}</div><div><small>PSEUDO LOCAL</small><h2>${esc(s.pseudo||'Curieux')}</h2></div><div class="big-score"><strong>${s.points}</strong><span>points</span></div></div><div class="metrics"><div><strong>${s.correct}</strong><span>bonnes réponses</span></div><div><strong>${s.played}</strong><span>questions jouées</span></div><div><strong>${s.best}</strong><span>meilleure session</span></div></div><div class="shared-board"><div class="board-head"><b>Classement partagé</b><button class="button secondary" id="refresh-board">Actualiser</button></div><p class="board-note">Résultats des QCM vérifiés par le serveur.</p><div id="leaderboard">${leaderboardMarkup()}</div></div><button class="button secondary" id="reset">Réinitialiser mes résultats</button></section>`}
function leaderboardMarkup(){return state.leaderboard.length?`<ol class="leader-list">${state.leaderboard.map((e,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><b>${esc(e.name)}</b><strong>${e.score} / ${e.total}</strong></li>`).join('')}</ol>`:'<p class="empty">Aucun score partagé pour le moment.</p>'}
async function loadLeaderboard(){try{let r=await fetch('/api/leaderboard');if(r.ok){state.leaderboard=(await r.json()).entries||[];let el=document.querySelector('#leaderboard');if(el)el.innerHTML=leaderboardMarkup()}}catch(e){let el=document.querySelector('#leaderboard');if(el)el.innerHTML='<p class="empty">Classement indisponible : lancez server.js pour le partager.</p>'}}

function render(){let h=location.hash.slice(1)||'catalogue',x=state.data.find(i=>h==='reaction-'+i.id);state.route=x?'detail':h;let out=state.route==='detail'?detail(x):state.route==='games'?games():state.route==='quiz'?quiz():state.route==='survival'?quiz(true):state.route==='memory'?memory():state.route==='mechanism'?mechanism():state.route==='score'?score():catalogue();document.querySelector('#app').innerHTML=out;bind();if(state.route==='score')loadLeaderboard();}
function bind(){document.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>{state.family=b.dataset.family;render()});let search=document.querySelector('#search');if(search)search.oninput=e=>{state.query=e.target.value;render();document.querySelector('#search')?.focus()};document.querySelector('#reset')?.addEventListener('click',()=>{localStorage.removeItem(scoreKey);render()});document.querySelector('#server-start')?.addEventListener('click',()=>startServerQuiz().catch(e=>{let x=document.querySelector('#server-name');if(x)x.insertAdjacentHTML('afterend','<p class="feedback">Serveur indisponible : lancez node server.js.</p>')}));document.querySelector('#server-submit')?.addEventListener('click',()=>submitServerScore());document.querySelector('#refresh-board')?.addEventListener('click',()=>loadLeaderboard());document.querySelectorAll('[data-server-answer]').forEach(b=>b.onclick=()=>serverAnswer(+b.dataset.serverAnswer));document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(+b.dataset.answer));document.querySelectorAll('.mem').forEach(b=>b.onclick=()=>flip(+b.dataset.i));}
function answer(id){let q=state.quiz||{cur:state.data[Math.floor(Math.random()*state.data.length)],score:0,streak:0,number:1};let ok=id===q.cur.id,fb=document.querySelector('#feedback');document.querySelectorAll('[data-answer]').forEach(b=>b.disabled=true);document.querySelector(`[data-answer="${id}"]`)?.classList.add(ok?'correct':'wrong');if(!ok)document.querySelector(`[data-answer="${q.cur.id}"]`)?.classList.add('correct');if(ok){q.score+=10+q.streak*2;q.streak++}else q.streak=0;if(fb)fb.innerHTML=ok?'Bonne réponse.':'La bonne réponse était <b>'+esc(q.cur.name)+'</b>.';let s=loadScore();s.points+=ok?10:0;s.correct+=ok?1:0;s.played++;if(q.mode==='survival'&&!ok){s.survival=Math.max(s.survival,q.score);s.best=Math.max(s.best,q.score);saveScore(s);setTimeout(()=>{state.quiz=null;location.hash='score'},700);return}saveScore(s);setTimeout(()=>{q.number++;q.cur=state.data[Math.floor(Math.random()*state.data.length)];state.quiz=q;render()},700)}
let open=[],moves=0,found=0,memCards=[];function flip(i){let b=document.querySelector(`[data-i="${i}"]`),c=memCards[i];if(!c||b.classList.contains('matched')||open.some(x=>x.i===i)||open.length===2)return;b.classList.add('open');b.innerHTML=c.type==='img'?image(c,'image_schema','Schéma'):esc(c.name);open.push({i,c,b});if(open.length===2){moves++;let[a,z]=open;if(a.c.id===z.c.id&&a.c.type!==z.c.type){a.b.classList.add('matched');z.b.classList.add('matched');found++;open=[]}else setTimeout(()=>{a.b.classList.remove('open');z.b.classList.remove('open');a.b.textContent=z.b.textContent='✦';open=[]},650);document.querySelector('#mfeedback').textContent=`Trouvées : ${found} / 6 · Coups : ${moves}`;if(found===6)setTimeout(()=>{location.hash='games'},700)}}
window.addEventListener('hashchange',render);document.addEventListener('click',e=>{if(e.target.matches('a[href="#memory"]')){let chosen=pick(state.data,6);memCards=shuffle(chosen.flatMap(x=>[{...x,type:'name'},{...x,type:'img'}]));open=[];moves=0;found=0}});fetch('data.json').then(r=>r.json()).then(d=>{state.data=d;render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js')}).catch(()=>{document.querySelector('#app').innerHTML='<p class="empty">Les données n’ont pas pu être chargées. Lancez l’application avec un serveur local.</p>'});
